name: movie
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.2.0
  animated_splash_screen: ^1.3.0
  shared_preferences: ^2.3.2
  percent_indicator: ^4.2.3
  auto_route: ^7.9.2
  flutter_bloc: ^8.1.6 
  dio: ^5.5.0+1
  freezed_annotation: ^2.4.4
  freezed: ^2.5.2
  http: ^1.2.2
  get_it: ^7.7.0
  smooth_page_indicator: ^1.2.0+3
  equatable: ^2.0.0
  sqflite: ^2.3.3+1
  path: ^1.9.0
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.9
  json_serializable: ^6.8.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
